name: server
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  core:
    path: ../../packages/core/
  grpc: ^3.1.0
  path: ^1.8.3
  redis: ^3.1.0
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
