name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  freezed_annotation: ^2.4.1
  grpc: ^3.2.3
  protobuf: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  lints: ^2.0.0
  test: ^1.21.0
